### PR TITLE
Detour based code

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
As you said:

> I'm merging this as-is, but I do have a few questions about the detouring method.
> 
> Namely, how does it deal with local variables? are they unable to be used, or is there some way to access the variables from the class getting its functions replaced?

Private fields of the class are accessed through `System.Reflection`.
Private methods are also accessed through `System.Reflection` and then invoked, although for some method overrides, you need to specify the types of the arguments that they take, or it causes an `AmbiguousMatchException`.

**Comment by RosaryMala** [comment]
I'm having trouble building this. Says
"'DefaultTool' does not contain a definition for 'FindSecondarySegment'"

**Comment by ghost** [comment]
I think you're talking about Line 289 in FakeNetTool.cs:
`flag2 = DefaultTool.FindSecondarySegment(num) != 0;`
Are your references to Assembly-CSharp.dll and all other assemblies working? That might be it.

**Comment by ghost** [comment]
Crash Report! Seems that the following code is error-prone.
`NetTool netTool = UnityEngine.Object.FindObjectOfType<ToolController>().gameObject.GetComponent<NetTool>();`
Maybe the following replacement fixes the problem:
`NetTool netTool = ToolsModifierControl.GetTool<NetTool>();`

> 000000013F573E16 (Cities) Scripting::ScriptingWrapperFor
> 0000000004C5487C (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Object:FindObjectsOfType (System.Type)
> 0000000004C5479D (Mono JIT Code) UnityEngine.Object:FindObjectOfType (System.Type)
> 0000000041454599 (Mono JIT Code) UnityEngine.Object:FindObjectOfType<object> ()
> 0000000071F03DB5 (Mono JIT Code) FineRoadHeights.FakeNetTool:GetElevation (NetInfo)
> 000000000EA00920 (Mono JIT Code) NetTool:SimulationStep ()
> 0000000071EF1800 (Mono JIT Code) ToolManager:SimulationStepImpl (int)
> 0000000071EF171D (Mono JIT Code) SimulationManagerBase`2<object, object>:SimulationStep (int)
> 0000000071EF1695 (Mono JIT Code) ToolManager:ISimulationManager.SimulationStep (int)
> 0000000004CF0514 (Mono JIT Code) SimulationManager:SimulationStep ()
> 0000000004CD236B (Mono JIT Code) SimulationManager:SimulationThread ()
> 0000000004C18BBB (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
> 000007FEE8823DF7 (mono) mono_set_defaults
> 000007FEE87782A1 (mono) mono_runtime_invoke
> 000007FEE87A1647 (mono) mono_thread_interruption_request_flag
> 000007FEE885676D (mono) unity_mono_method_is_generic
> 00000000772059CD (kernel32) BaseThreadInitThunk
> 000000007733B891 (ntdll) RtlUserThreadStart

**Pull request merged**
