### PR TITLE
Updated for Snowfall (plus some unwanted formatting by Visual Studio)

### PR DESCRIPTION
**Pull request by PropaneDragon**
This should be working for Snowfall. There's probably more that needs changing, but this should do for now.

### CODE REVIEW

**Comment by RosaryMala** [comment]
I don't play skylines andmore, and don't have snowfall, so I think it's better of somebody copies this with the fix and uploads it to the workshop.

**Comment by PropaneDragon** [comment]
Shame. I'll branch off and make my own build then. Thanks for the awesome mod up until now though!

**Comment by PropaneDragon** [comment]
Are you pushing these changes up?

**Comment by RosaryMala** [comment]
I'll see.

**Pull request merged**
